### ISSUE TITLE
Uncaught ReferenceError: createPageChooser is not defined

### ISSUE THREAD

**Issue by mwvolo** [torchbox/wagtail-import-export#5]
When trying to select a page to import to/export from I get the following error in the console.

`Uncaught ReferenceError: createPageChooser is not defined`

I'll be happy to submit a bug fix if I can figure out what it should be now! I'm running Wagtail 2.3.

**Comment by nealtodd** [comment]
Hi @mwharrison,

Sorry for the radio silence on this repo, it isn't one we've been actively using recently.

The error stems from the use of the `AdminPageChooser` widget in [forms.py](https://github.com/torchbox/wagtail-import-export/blob/master/wagtailimportexport/forms.py#L20). It's not immediately obvious why the JS `createPageChooser` method doesn't now get into the page.

If you can figure it out and submit a PR fix that'd be great. Otherwise I'll try to take a look at it myself in the next week or two.

**Comment by nealtodd** [comment]
(As a very temporary workaround, commenting out the widget line in the forms will get it to work, albeit meaning you need to enter the ID of the source/destination page instead. I realise that's a pain both for using the package and the UI!)

**Comment by gasman** [comment]
From a quick glance, I suspect it's now necessary to output the form media onto the template (`{{ form.media.js }}` and `{{ form.media.css }}`), as per https://github.com/wagtail/wagtail/pull/4574

**Comment by nealtodd** [comment]
Thanks for the reference Matthew! Yep, that looks like it would be it. I'll verify this week and make a new PyPI release with the fix.
